### ISSUE TITLE
Build fail when using migrator

### ISSUE THREAD

**Issue by vishnuprasad-95** [kafkas/firecode#37]
```
node_modules/@firecode/admin/lib/api/interfaces/Migrator.d.ts:166:39 - error TS1005: ',' expected.
```

**Comment by vishnuprasad-95** [comment]
More info in the error console:
```
renameFields(...changes: [oldField: string | firestore.FieldPath, newField: string | firestore.FieldPath][]): Promise<MigrationResult>;
```

**Comment by kafkas** [comment]
@vishnuprasad-95 What are your `typescript` and `@firecode/admin` versions?

**Comment by vishnuprasad-95** [comment]
"@firecode/admin": "^0.11.0",
"typescript": "^3.8.0"

**Comment by vishnuprasad-95** [comment]
@kafkas guess it was the old typescript version.. Upgraded to latest ts and build is now good.
Sorry to bother. My ignorance !
